### ISSUE TITLE
linode.errors.ApiError: 400: Linode busy

### ISSUE THREAD

**Issue by rcdeoliveira** [linode/python-linode-api#110]
Hello everyone, I don't know if my issue is something that I don't understand or a bug. I am trying to implement a python script to provisioning linodes, but I am having issues following next steeps:
1) create linode
2) add private 
3) add root disk (with stackscript)
4) add swap disk
My issue comes sometimes on steeps 2 or 3, very often I get the following error: "linode.errors.ApiError: 400: Linode busy.", If I add few seconds of delay between every steep usually it works, but I would like to know the following:
- How can I determine if the linode is busy or not? (linode.status seams to be something apart from this "state")

Thank you so much.

**Comment by Dorthu** [comment]
The Linode is busy if it's status is anything other than "running" or "offline".

You can probably get around some of the frustration by deploying the Linode from an image and stackscript ([as described here under "Creating a Linode from StackScript](http://python-linode-api.readthedocs.io/en/latest/linode/linode_client.html#linode.linode_client.LinodeGroup.create_instance)).  It might look something like this:

```python
new_linode = client.linode.create_instance("g5-standard-2", "us-east", image="linode/debian9",
                                                                        stackscript=1234, root_pass="strongPassword")
private_ip = new_linode.allocate_ip()
```

This will create a Linode running the `linode/debian9` image (and with a swap disk) and the StackScript 1234, then allocate a private IP for it - and it'll boot as soon as it's ready.  Since it's all happening in one request, you won't run into the issue of the Linode being busy provisioning when you try to deploy the image.

Let me know if this helps.

**Comment by rcdeoliveira** [comment]
Hi @Dorthu , thank you so much for your help.

I tested your example and it works flawlessly, but if I use the example described in "[Creating a Linode from StackScrip](http://python-linode-api.readthedocs.io/en/latest/linode/linode_client.html#linode.linode_client.LinodeGroup.create_instance)t" (I need to provide UDF values) I get another error:

```
Traceback (most recent call last):
  File "./test-stackscript.py", line 12, in <module>
    new_linode, password = myClient.linode.create_instance( "g5-standard-2", "us-east", image="linode/debian9", stackscript=stackscript, stackscript_data={"gh_username": "example"})
  File "/home/rcdeoliveira/.local/lib/python3.6/site-packages/linode/linode_client.py", line 239, in create_instance
    kwargs["stackscript_id"] = (kwargs["stackscript"].id if issubclass(kwargs["stackscript"])
TypeError: issubclass expected 2 arguments, got 1

```

My code is as follows:

```
from linode import LinodeClient, StackScript

myToken = 'secretetocken'
myClient = LinodeClient(myToken)

stackscript = StackScript(myClient, 10079)

new_linode, password = myClient.linode.create_instance( "g5-standard-2", "us-east", image="linode/debian9", stackscript=stackscript, stackscript_data={"gh_username": "example"})
```

**Comment by rcdeoliveira** [comment]
Thanks @Dorthu  for your help and quick fix, it works like a charm!
