### ISSUE TITLE
Improves Linode.create_config 

### ISSUE THREAD

**Issue by adontz** [linode/python-linode-api#60]
Regarding https://github.com/linode/python-linode-api/commit/a95285c892389dd36b80c431cd3c0950ccd00beb 

First of all there is unconditional "raise TypeError('oops')" now.
Second, as far as I can see there is now way to map sda=disk, sdb=volume, sdc=disk with new code,
Not to offend anyone, but new code looks to me as invalid try to fix IDK what.

**Comment by Dorthu** [comment]
Wow, that's embarrassing.

That commit was made to address issues with https://github.com/linode/python-linode-api/pull/56, namely that passing in any volumes along with disks would overwrite the disks given (the first volume would replace the first disk as `sda` and so on).  Leaving debugging code in was obviously not intentional.

I don't see specifying what ends up in what slot explicitly as very high priority at this time - while the api does support it, I can't think of a good interface for it, and I think it's plenty intuitive that the disks map to the devices in order, followed by the volumes.  I will revisit it again in the future if I can come up with an interface that isn't overly confusing.

**Comment by Dorthu** [comment]
This was released in v4.1.4b2

**Comment by adontz** [comment]
For me new there are two problems with new code. First I have mentioned before, there is no way, compared to my original version, to map disk, volume, disk, which is artificial limitation. Second, now disk indices are absolute and volume indices are relative. Relative volume indices which shift mapped device name based on disk count look like bad design for me. If you are making an API which allows everything cloud.linode.com can do, then this is not right. I may suggest a two options:

1) Use single array devices. If element is Disk or Volume object act accordingly, if integer id assume it to be disk. I don't like it because ("Explicit is better than implicit.", "In the face of ambiguity, refuse the temptation to guess.")
2) Use two separate arrays disks and volumes and just check at run time if both are valid and have not None elements at the same indices.

I am which server orchestration software now and I want Linode support to be as flexible as possible. Please? :-D

**Comment by Dorthu** [comment]
One combined array makes sense to me. I'll give it another shot tonight

**Comment by adontz** [comment]
Sorry for reopening, but I think this is the last time.
https://github.com/linode/python-linode-api/pull/62
